#!/bin/bash

[[ $1 = '' ]] && echo "Usage: smpolicy <SMA_branch_name>" && exit 1

./apply.sh --org-url https://msazure.visualstudio.com --proj-name One --repo-name Networking-Datapath-HostSdnStack-SMAgent --branch "$1" --pipeline-name Overlake-Build-PullRequest

echo "If it's not working, make sure your PAT has FULL permission to EVERYTHING!!!"
echo "Build at"
echo "    https://msazure.visualstudio.com/One/_build?definitionId=285519&_a=summary"
microsoft-edge-stable --disable-features=msUndersideButton "https://msazure.visualstudio.com/One/_build?definitionId=285519&_a=summary"

# repo_id: 12e0c399-4e80-42b6-aff2-dc693505d5f7
# build_definition_id: 270313

