#!/bin/bash

[[ $1 = '' ]] && echo "Usage: $0 <branch_name>" && exit 1

./apply.sh --org-url https://msazure.visualstudio.com --proj-name One --repo-name Networking-Datapath-HostSdnStack-VFP --branch "$1" --pipeline-name Overlake-Build-PullRequest

# echo "If it's not working, make sure your PAT has FULL permission to EVERYTHING!!!"
# echo "Build at"
# echo "    https://msazure.visualstudio.com/One/_build?definitionId=285519&_a=summary"
# microsoft-edge-stable --disable-features=msUndersideButton "https://msazure.visualstudio.com/One/_build?definitionId=285519&_a=summary"
