#!/bin/bash
_dom="$1"
_slient=1
_help="Usage: $0 <args...>
Website:       $0 example.com
Extra Mailbox: $0 xxx@recolic.net
Named Host:    $0 hms.recolic
               $0 ms.recolic
               $0 pc.recolic
               $0 drive.recolic
Unnamed Host:  $0 10.100.100.1
Other use:     $0 toy1@dummy
"

[[ "$_dom" = "" ]] && echo "$_help" && exit 19
[[ "$_dom" = "s" ]] && _slient=1 && _dom="$2" && shift

shift

if [[ $_slient = 0 ]]; then
    SEED=$(rsec PSWDGEN_SECRET) &&
    printf '%s' "$SEED" | _pswdGen-dynlink -s - -f $_dom -y $* -l 16
else
    SEED=$(rsec PSWDGEN_SECRET) &&
    printf '%s' "$SEED" | _pswdGen-dynlink -s - -f $_dom -y $* -l 16 | sed 's/^.* //g' | tr -d '\n'
fi

