<?php
require_once $_SERVER['DOCUMENT_ROOT'] . "/rlib.php";

function load_webauthn_credential_record($k) {
  // die() if key not found
  return rsec("FIDO_CRED_REC_$k");
}

function get_login_parameters() {
  $k = $_GET['k'] ?? die("fatal error: k not set");
  $cb = $_GET['cb'] ?? null;
  return [$k, $cb];
}

function on_login_success($k, $cb) {
  $loginValidThru = time()+15*24*60*60; // cookie valid for 15 days
  $stateString = rauth_login($k, $loginValidThru);
  setcookie("rauth", "$stateString", ["expires" => $loginValidThru, "path" => "/", "secure" => true]);
  if ($cb !== null) {
    header('Location: ' . $cb);
    echo "<h1>Login success! Sending you back...</h1>";
    exit;
  }
  die("Error: Login Success, but missing callback URL!");
}

function on_login_failure() { die('Error: Invalid passkey.'); }

///////////////////////// BEGIN LIBRARY CODE /////////////////////////////////
/////////////////////////Generated by GPT 5.6 sol // HUMAN DO NOT MODIFY /////

session_start();

function b64u_encode($value) { return rtrim(strtr(base64_encode($value), '+/', '-_'), '='); }
function b64u_decode($value) { $result = base64_decode(strtr($value, '-_', '+/'), true); if ($result === false) on_login_failure(); return $result; }
function request_origin() { return $_SERVER['HTTP_ORIGIN'] ?? ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST']); }
function load_credential_record($k) { $record = json_decode(b64u_decode(load_webauthn_credential_record($k)), true); if (!is_array($record) || ($record['v'] ?? 0) !== 1) on_login_failure(); return $record; }
function der_to_pem($der) { return "-----BEGIN PUBLIC KEY-----\n" . chunk_split(base64_encode($der), 64, "\n") . "-----END PUBLIC KEY-----\n"; }

[$k, $cb] = get_login_parameters();

if (($_GET['action'] ?? '') === 'options') {
  $record = load_credential_record($k);
  $challenge = random_bytes(32);
  $_SESSION['webauthn_login_challenge'] = $challenge;
  header('Content-Type: application/json');
  echo json_encode(['challenge' => b64u_encode($challenge), 'credentialId' => $record['id'], 'rpId' => $record['rp']]);
  exit;
}

if (($_GET['action'] ?? '') === 'finish') {
  $data = $_POST;
  $record = load_credential_record($k);
  $challenge = $_SESSION['webauthn_login_challenge'] ?? null;
  unset($_SESSION['webauthn_login_challenge']);
  if (!is_array($data) || !is_string($challenge) || !hash_equals($record['id'], $data['credentialId'] ?? '')) on_login_failure();
  $client_json = b64u_decode($data['clientDataJSON'] ?? '');
  $client = json_decode($client_json, true);
  if (!is_array($client) || ($client['type'] ?? '') !== 'webauthn.get') on_login_failure();
  if (!hash_equals(b64u_encode($challenge), $client['challenge'] ?? '') || !hash_equals(request_origin(), $client['origin'] ?? '')) on_login_failure();
  $auth_data = b64u_decode($data['authenticatorData'] ?? '');
  if (strlen($auth_data) < 37 || !hash_equals(hash('sha256', $record['rp'], true), substr($auth_data, 0, 32))) on_login_failure();
  $flags = ord($auth_data[32]);
  if (($flags & 0x01) === 0 || ($flags & 0x04) === 0) on_login_failure();
  $signed = $auth_data . hash('sha256', $client_json, true);
  $result = openssl_verify($signed, b64u_decode($data['signature'] ?? ''), der_to_pem(b64u_decode($record['key'] ?? '')), OPENSSL_ALGO_SHA256);
  if ($result !== 1) on_login_failure();
  on_login_success($k, $cb);
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Passkey login</title>
  <style>body { max-width: 32rem; margin: 3rem auto; padding: 0 1rem; font: 16px/1.5 system-ui, sans-serif; } button { padding: .6rem .9rem; } pre { padding: 1rem; border: 1px solid #aaa; white-space: pre-wrap; }</style>
</head>
<body>
  <h1>Passkey login</h1>
  <button id="login">Login</button>
  <pre id="output"></pre>
  <script>
    const output = document.querySelector('#output');
    const fromB64u = value => Uint8Array.from(atob(value.replaceAll('-', '+').replaceAll('_', '/').padEnd(Math.ceil(value.length / 4) * 4, '=')), c => c.charCodeAt(0));
    const toB64u = value => btoa(String.fromCharCode(...new Uint8Array(value))).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '');
    const endpoint = action => { const url = new URL(location.href); url.searchParams.set('action', action); return url; };
    document.querySelector('#login').onclick = async () => {
      try {
        const optionsResponse = await fetch(endpoint('options'));
        if (!optionsResponse.ok) throw new Error(await optionsResponse.text());
        const options = await optionsResponse.json();
        const credential = await navigator.credentials.get({ publicKey: { challenge: fromB64u(options.challenge), rpId: options.rpId, allowCredentials: [{ type: 'public-key', id: fromB64u(options.credentialId) }], userVerification: 'required', timeout: 120000 } });
        const body = { credentialId: toB64u(credential.rawId), clientDataJSON: toB64u(credential.response.clientDataJSON), authenticatorData: toB64u(credential.response.authenticatorData), signature: toB64u(credential.response.signature) };
        const form = document.createElement('form');
        form.method = 'post';
        form.action = endpoint('finish');
        for (const [name, value] of Object.entries(body)) { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = value; form.append(input); }
        document.body.append(form);
        form.submit();
      } catch (error) { output.textContent = `${error.name}: ${error.message}`; }
    };
  </script>
</body>
</html>
