#!/bin/bash

[[ -f /usr/bin/beep ]] && /usr/bin/beep && exit 0

# beep is not available on some devices... Use this as replacement.
alarm_fish_vol=70% alarm_fish_file=/usr/share/sounds/freedesktop/stereo/bell.oga alarm_fish_beep_once=1 alarm.fish 0

