#!/bin/bash

[[ -f /usr/bin/beep ]] && /usr/bin/beep && exit 0

# beep is not available on some devices... Use this as replacement.
pactl set-sink-volume 0 80%
paplay /usr/share/sounds/freedesktop/stereo/bell.oga
