#!/bin/fish
# version 1.03: allows setting env target_line
# version 1.04: if target_name starts with @, it is ssh target (customize port not supported yet). Allows bash command in password.

function die
    echo $argv 1>&2
    exit 1
end

set target $argv[1]
if test -z $target
    set target help
end

set targets "
NAME|USERNAME|PASSWORD|HOSTNAME
msdev|recolic|$R_SEC_DEVBOX|proxy-cdn.recolic.net:30623
msdev-backup|recolic|$R_SEC_DEVBOX|proxy-cdn.recolic.net:30624
labjump|fareast\bensl|$R_SEC_WEAK12|10.209.180.22
lanbox|recolic|$R_SEC_WEAK10|10.100.100.101:30473
cnbox|recolic|$R_SEC_WEAK10|proxy-cdn.recolic.net:30625
host16|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.18.31
host18|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.18.29
host32|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.10.94
host33|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.10.92
host1030|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.10.37
host2021|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.15.30
kedardbg|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.12.79
kedardbg2|local\Administrator|$R_SEC_OVL_HOST_RDP|10.10.12.80
tmpvsbox|recolic|$R_SEC_WEAK10|localhost:30477
@openwrt|root|sh://genpasswd 10.100.100.1|10.100.100.1
"

if test $target = help
    echo "Usage: rrdp <target_name>"
    echo "Target list:"
    echo $targets | grep -v '^NAME' | cut -d '|' -f 1 | grep . | string join ', '
    echo "or Usage: env 'target_line=|Administrator|password|my-vm.example.com:3389' rrdp ."
    exit 0
end

test -n "$target_line"
or set target_line (echo $targets | grep "^$target|")
or die "Target $target not found."
set user (echo $target_line | cut -d '|' -f 2)
set pass (echo $target_line | cut -d '|' -f 3)
set host (echo $target_line | cut -d '|' -f 4)

if string match "sh://*" $pass > /dev/null
    # need to expand password
    set pass_command (echo $pass | sed 's|sh://||')
    set pass (bash -c "$pass_command")
    or exit $status
end

if string match "@*" $target_line > /dev/null
    # SSH
    sshpass -p $pass ssh $user@$host
else
    # RDP
    if test $XDG_SESSION_TYPE = x11
        set resolution (xrandr | grep -o 'current [0-9]* x [0-9]*')
        set w (echo $resolution | cut -d x -f 1 | grep -o '[0-9]*')
        set h (math (echo $resolution | cut -d x -f 2 | grep -o '[0-9]*')-100)
        # current 1920 x 1080
        if which xfreerdp
            set rdp xfreerdp
        else
            set rdp xfreerdp3
        end
    else if test $XDG_SESSION_TYPE = wayland
        # Xwayland is also working
        set resolution (xrandr | grep -o 'current [0-9]* x [0-9]*')
        set w (echo $resolution | cut -d x -f 1 | grep -o '[0-9]*')
        set h (math (echo $resolution | cut -d x -f 2 | grep -o '[0-9]*')-50)
        # For wayland, fullscreen is acceptable because shortcuts are not captured on deny
        if which wlfreerdp
            set rdp wlfreerdp
        else
            set rdp xfreerdp3
            set h (math $h-50)
            # clipboard doesnt work in wlfreerdp3 sdl-freerdp3
        end
    else
        die "Unknown XDG_SESSION_TYPE $XDG_SESSION_TYPE"
    end
    
    if string match '*win7*' $target
        set rdp rdesktop
    end
    
    if test $rdp = rdesktop
        echo "EXEC: $rdp -g $w'x'$h -r disk:abc=/home/recolic/Downloads -u $user -p $pass -v $host"
        $rdp -K -g $w'x'$h -r disk:abc=/home/recolic/Downloads -u $user -p $pass -v $host
    else
        echo "EXEC: $rdp -disable-grab-keyboard -disable-toggle-fullscreen -w $w -h $h -drive mapped_tmp,$HOME/tmp -u $user -p $pass -v $host"
        $rdp -disable-grab-keyboard -disable-toggle-fullscreen -w $w -h $h -drive mapped_tmp,$HOME/tmp -u $user -p $pass -v $host
        # disable krb5: /auth-pkg-list:!kerberos 
    end
end

exit $status

